In [32]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [33]:
print(arr)

[1 2 3 4 5 6]


In [34]:
type(arr)

numpy.ndarray

In [35]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [36]:
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
matrix2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
matrix1+matrix2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [41]:
add_matrix=matrix1+matrix2

In [42]:
print(add_matrix)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [43]:
l1=[10,20,30]
l2=[40,50,60]
vector1=np.array(l1)
vector2=np.array(l2)

In [44]:
add_vactor=vector1+vector2

In [45]:
print(add_vactor)

[50 70 90]


In [46]:
ele=[1,1,1]
print(vector1+ele)

[11 21 31]


In [47]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
ele+matrix1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [49]:
l1=[[1,2,3,4],[4,5,6,7],[2,7,8,9],[9,5,1,2]]
l2=[[1,2,3,4],[4,5,6,7],[2,7,8,9],[9,5,1,2]]
a=np.array(l1)
b=np.array(l1)
#MULTIPLICATION IS DONE ACCOTDING TO THERE POSITION ONLY DOT PRODUCT
print("Multiplication is...")
print(a*b)# This is the normal element to element multipliation
dot_product=np.dot(a,b)
print("Using dot product")
print(dot_product)#but this is actual matrix multiplication

Multiplication is...
[[ 1  4  9 16]
 [16 25 36 49]
 [ 4 49 64 81]
 [81 25  1  4]]
Using dot product
[[ 51  53  43  53]
 [ 99 110  97 119]
 [127 140 121 147]
 [ 49  60  67  84]]


In [50]:
# Write code to create a dataframe from a dictionary and display it.
# Sample data: {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
df={'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
df


{'X': [78, 85, 96, 80, 86],
 'Y': [84, 94, 89, 83, 86],
 'Z': [86, 97, 96, 72, 83]}

In [51]:
import pandas as pd
dataframe=pd.DataFrame()
print(dataframe)

Empty DataFrame
Columns: []
Index: []


In [52]:
list1=list(df)
list1

['X', 'Y', 'Z']

In [53]:
key=df.keys()

In [54]:
key

dict_keys(['X', 'Y', 'Z'])

In [55]:
print(key)

dict_keys(['X', 'Y', 'Z'])


In [56]:
len(key)

3

In [57]:
values=df.values()
print(values)

dict_values([[78, 85, 96, 80, 86], [84, 94, 89, 83, 86], [86, 97, 96, 72, 83]])


In [58]:
df

{'X': [78, 85, 96, 80, 86],
 'Y': [84, 94, 89, 83, 86],
 'Z': [86, 97, 96, 72, 83]}

In [59]:
df


{'X': [78, 85, 96, 80, 86],
 'Y': [84, 94, 89, 83, 86],
 'Z': [86, 97, 96, 72, 83]}

In [60]:
df={'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
df

{'X': [78, 85, 96, 80, 86],
 'Y': [84, 94, 89, 83, 86],
 'Z': [86, 97, 96, 72, 83]}

In [61]:
df

{'X': [78, 85, 96, 80, 86],
 'Y': [84, 94, 89, 83, 86],
 'Z': [86, 97, 96, 72, 83]}

In [62]:
keys=df.keys()
a=[df[key] for key in keys]
a

[[78, 85, 96, 80, 86], [84, 94, 89, 83, 86], [86, 97, 96, 72, 83]]

In [63]:
df


{'X': [78, 85, 96, 80, 86],
 'Y': [84, 94, 89, 83, 86],
 'Z': [86, 97, 96, 72, 83]}

In [64]:
df={'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
df


{'X': [78, 85, 96, 80, 86],
 'Y': [84, 94, 89, 83, 86],
 'Z': [86, 97, 96, 72, 83]}

In [65]:
import pandas as pd
dataframe=pd.DataFrame(df)
print(dataframe)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [66]:
#QUESTION-2
exam_data = {
'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura',
'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
            }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(exam_data,labels)
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [67]:
df[1:4]

name  score  attempts qualify
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no

In [68]:
df


name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [72]:
df.iloc[[4,5,9],[2,3]]

attempts qualify
e         2      no
f         3     yes
j         1     yes

In [39]:
names=df['name'].tolist()

In [40]:
names

['Anastasia',
 'Dima',
 'Katherine',
 'James',
 'Emily',
 'Michael',
 'Matthew',
 'Laura',
 'Kevin',
 'Jonas']

In [41]:
selectd_column=['name','score']
names=df[selectd_column]
print(names)

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [42]:
selected_row=['a','c','e','g']
df.loc[selected_row,selectd_column]

name  score
a  Anastasia   12.5
c  Katherine   16.5
e      Emily    9.0
g    Matthew   14.5

In [43]:
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [44]:
attempts=df["attempts"].tolist()

In [45]:
attempts

[1, 3, 2, 3, 2, 3, 1, 1, 2, 1]

In [46]:
new_row=[]
for i in attempts:
    if i>2:
        new_row.append(i)

In [47]:
new_row

[3, 3, 3]

In [48]:
new_lables=[]
for i in range(len(labels)):
    for j in new_row:
        if j==(i+1):
            new_lables.append(labels[i])
print(new_lables)

['c', 'c', 'c']


In [49]:
labels

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [50]:
df[:]

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [51]:
df1=df['attempts']>2

In [52]:
df[df1]

name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

In [53]:
print(df.loc[df['attempts'] >2])

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


In [54]:
df[df['attempts']>2]

name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

In [55]:
df[df['score'].isnull()]

name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

In [31]:
df.count()

NameError: name 'df' is not defined

In [57]:
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [58]:
df


name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [59]:
df.drop(df[df[‘name’] == 'Dima'].index)

SyntaxError: invalid character '‘' (U+2018) (2857598288.py, line 1)

In [ ]:
 d1=df[df['name'] != 'Dima']

In [ ]:
d1

In [ ]:
d1.index

In [ ]:
delete_index=df[df['name']=='Dima'].index
print(delete_index)

In [ ]:
df.drop(delete_index)

In [ ]:
df

In [ ]:
indes=df.index

In [ ]:
indes

In [ ]:
#new_index=eval(input("Enter new index names: "))

In [ ]:
names=df['name'].tolist()

In [ ]:
names

In [ ]:
print(names)

In [ ]:
name=df["name"].tolist()

In [ ]:
name

In [ ]:
print(name)

In [ ]:
df(exam_data,name)

In [ ]:
dateframe=df(exam_data,name)

In [ ]:
exam_data

In [ ]:
df=pd.DataFrame(exam_data)

In [ ]:
df

In [ ]:
df=pd.DataFrame(exam_data,name)

In [ ]:
df

In [ ]:
print(df[James])

In [ ]:
df.index

In [ ]:
print(df.loc['James'])
      

In [ ]:
row=df.loc['James']
row

In [ ]:
df.fillna(111,inplace=True)

In [ ]:
df

In [ ]:
df=df.reset_index()

In [ ]:
df

In [ ]:
cource=eval(input("Enter the number of cource: "))
fees=eval=(input("Enter fess: "))
z=zip(cource,fees)
z

In [ ]:
[(i,j) for i,j in z]

In [ ]:
c=input("Enter the number of cource: ")
f=input("Enter fess: ")
cource=c.split(",")
fees=f.split(",")
z=zip(cource,fees)
a=list(z)
print(a)

In [ ]:
d=dict(a)
print(d)

In [ ]:
df1=pd.DataFrame(d,[11,22,33,44,55])
df1

In [ ]:
dataset = pd.read_csv("annual-enterprise-survey-2021-financial-year-provisional-csv.csv")  

In [ ]:
dataset


In [ ]:
dataset.drop(41714)#Used for droping a perficular row value

In [ ]:
dataset

In [ ]:
dataset.drop(41714) #By default it will taka as a vlaue as axix=0 means row and specified row number

In [ ]:
dataset.drop(2,axis=0) 

In [ ]:
dataset.drop("Industry_code_NZSIOC",axis=1) 

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x=[ i  for i in range(10,101,10)]
x

In [ ]:
y=[ i  for i in range(10,101,10)]
y

In [ ]:
plt.plot(x,y,'o',"green")

In [ ]:
plt.plot(x,y,'o')

In [ ]:
c=input("enter company name :")
company=[i for i in c.split(",")]
r=input("enter revinue price :")
revinue_pricec=[i for i in r.split(",")]
plt.plot(company,revinue_pricec)

In [ ]:
import numpy as np

In [ ]:
xpos=np.arange(len(revinue_pricec))

In [ ]:
xpos

In [ ]:
plt.bar(xpos,revinue_pricec)

In [ ]:
plt.xticks(xpos,company)
plt.bar(xpos,revinue_pricec,label="Revinue")
plt.legend()

In [ ]:
lis=[10,20,300,400,90]
k=list(eval('5622,51,42,52,5,'))
k

In [ ]:
for i in k:
    print(i)

In [ ]:
type(k[4])

In [ ]:
import numpy as np

In [ ]:
arr=np.array([[1,2,3,4,5,6]])

In [ ]:
arr

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])

In [ ]:
arr2

In [ ]:
def add(a:Vector,b:Vector)->List[float]:
    return  a+b
add([1,2,3],[4,5,7])

In [ ]:
from typing import List


In [ ]:
Vector=List[float]

In [ ]:
def add(v1:Vector,v2:Vector)->Vector:
    return [i+j for i,j in zip(v1,v2)]


In [ ]:
import numpy as np


In [ ]:
a1=np.array([1,1,2])

In [ ]:
a2=np.array([1,2,3])
add_list=add(a1,a2)
add_list

In [2]:
type(add_list)

NameError: name 'add_list' is not defined

In [3]:
alpha=[input("Enter a list of alpha :")]
alpha

Enter a list of alpha :a,b,c,d,e,f,e,g


['a,b,c,d,e,f,e,g']

In [4]:
alpha

['a,b,c,d,e,f,e,g']

In [5]:
alpha=eval("Enter ")

NameError: name 'Enter' is not defined

In [23]:
temp=eval(input("Enter something  :"))
# alpha=temp.split(",")
# alpha
temp

Enter something  :[a,d,d,f,f,]


NameError: name 'a' is not defined

In [ ]:
q,w,e,r,t,y,u,i,o,p,a,s,d,f,g,h,j,k,l,z,x,c,v,b,n,m,q,w,e,r

In [ ]:
1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,3,4

In [13]:
import numpy as np


In [14]:
arr=np.array([4,1,1,11,1,5])
arr

array([ 4,  1,  1, 11,  1,  5])

In [15]:
arr.shape

(6,)

In [16]:
r=np.array([[ 4,  1,  1, 11,  1,  5],[9,9,9,9,9,9,9]])
r

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [17]:
arr=np.array([[1, 2, 3],[4, 5, 6]])

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr.ndim

2

In [20]:
arr.shape

(2, 3)

In [21]:
arr[0]

array([1, 2, 3])

In [22]:
arr[1]

array([4, 5, 6])

In [23]:
arr[:,1]

array([2, 5])

In [25]:
print(np.add(arr,axis=0))

TypeError: add() takes from 2 to 3 positional arguments but 1 were given

In [26]:
np.multiply(2,5)

10

In [28]:
a1=np.array([1,2,3])
a2=np.array([1,2,3])
result=np.dot(a1,a2)
result

14

In [29]:
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[1,2,3],[4,5,6],[7,8,9]])
result=np.multiply(matrix1,matrix2)
result

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [30]:
result=np.dot(matrix1,matrix2)
result

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [79]:
mn=np.max(result)

In [80]:
mn

150

In [84]:
result(np.isnull())

AttributeError: module 'numpy' has no attribute 'isnull'

In [85]:
a1*a2

array([1, 4, 9])

In [1]:
print("hellpo")

hellpo
